nome= input("Escreva seu nome:")
cpf= input("Escreva seu cpf:")
endereco= input("Escreva seu endereco:")
idade= input("Escreva sua idade:")
altura= input("Escreva sua altura:")
telefone= input("Escreva seu telefone:")

print("Nome:", nome)
print("CPF:", cpf)
print("Endereco:", endereco)
print("Idade:", idade, "anos")
print("Altura:", altura,"metros")
print("Telefone:", telefone)
